[package]
name = "m_ary_partitions"
version = "0.1.0"
authors = ["a.haggi@yahoo.com <a.haggi@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
